# Generated by Django 6.0.2 on 2026-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Theft', 'Theft'), ('Fire', 'Fire'), ('Road Accident', 'Road Accident'), ('Medical Emergency', 'Medical Emergency'), ('Violence', 'Violence'), ('Natural Disaster', 'Natural Disaster'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('incident_datetime', models.DateTimeField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='incident_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='incident_audio/')),
                ('anonymous', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
