# Generated by Django 6.0.2 on 2026-07-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_incidentreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='status',
        ),
    ]
