# Generated by Django 6.0.2 on 2026-08-01 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('Medical Emergency', 'Medical Emergency'), ('Crime', 'Crime'), ('Fire', 'Fire'), ('Road Accident', 'Road Accident'), ('Violence', 'Violence'), ('Natural Disaster', 'Natural Disaster'), ('Suspicious Activity', 'Suspicious Activity'), ('Others', 'Others')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sos/photos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='sos/audio/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Responding', 'Responding'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('admin_remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
