# Generated by Django 6.0.2 on 2026-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_sosalert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sos/videos/'),
        ),
    ]
