# Generated by Django 6.0.2 on 2026-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_sosalert_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'SOS Alert', 'verbose_name_plural': 'SOS Alerts'},
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='audio',
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='emergency_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
