# Generated by Django 6.0.2 on 2026-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_alter_sosalert_options_remove_sosalert_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosalert',
            options={},
        ),
        migrations.AddField(
            model_name='sosalert',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='sos/audio/'),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='emergency_type',
            field=models.CharField(choices=[('Medical Emergency', 'Medical Emergency'), ('Crime', 'Crime'), ('Fire', 'Fire'), ('Road Accident', 'Road Accident'), ('Violence', 'Violence'), ('Natural Disaster', 'Natural Disaster'), ('Suspicious Activity', 'Suspicious Activity'), ('Others', 'Others')], max_length=50),
        ),
    ]
