# Generated by Django 6.0.2 on 2026-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('incident', 'Incident'), ('sos', 'SOS')], default='incident', max_length=20),
            preserve_default=False,
        ),
    ]
