# Generated by Django 6.0.2 on 2026-08-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type'),
        ('reports', '0006_alter_incidentreport_user'),
        ('sos', '0005_alter_sosalert_options_sosalert_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sos.sosalert'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.incidentreport'),
        ),
    ]
